# Analysis of Extra dataset by Ravin Kumar
A couple of hours into the data dive another dataset was releaased. As other teams were working on the original datasets and had already made some headway I decided to switch to this one to see what I could find

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
extra_path = r'Source Data/data/Extra/'

### First Challenge
If you look at the files, the descriptive headers are split between two rows and it's a bit hard to use them in codes and queries. If you reference the notes folder, the original dataset is present, but an extra sheet has been added that uniquely idenitifies each column of data

In [14]:
npo_df = pd.read_csv(extra_path + "NPO End of Project Evaluation - 2015.csv", skiprows = 2, prefix="npo_", header=None)
npo_df.head()

,npo_0,npo_1,npo_2,npo_3,npo_4,npo_5,npo_6,npo_7,npo_8,npo_9,...,npo_110,npo_111,npo_112,npo_113,npo_114,npo_115,npo_116,npo_117,npo_118,npo_119
0,4225978879,73895393,9/29/2015 14:02,9/29/2015 14:30,107.207.98.249,marianne@sfcla.org,Marianne,Reifer,Program Measurement service grant completed in...,St. Francis Center,...,NaN,1 - 5 %,NaN,NaN,We don’t have enough staff time to manage pro ...,NaN,NaN,NaN,NaN,NaN
1,4223713529,73895393,9/28/2015 16:01,9/28/2015 16:07,69.60.15.242,katie@shesthefirst.org,Katie,Riley,Annual Report service grant completed in Sep 2015,She's the First,...,NaN,Not sure,We prefer to hire employees or consultants to ...,We don’t have staff expertise to manage pro bo...,We don’t have enough staff time to manage pro ...,NaN,NaN,We don’t believe that pro-bono resources would...,These areas are too sensitive for pro-bono res...,NaN
2,4222631124,73895393,9/28/2015 5:17,9/28/2015 5:35,99.185.45.96,susanstewart@sbcglobal.net,Susan,Stewart,WordPress Website service grant completed in S...,Family Violence Law Center,...,NaN,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4217544425,73321917,9/24/2015 17:39,9/24/2015 17:59,64.41.186.174,mary@samaritanhousesanmateo.org,Mary,Dunbar,Key Messages & Brand Strategy service grant co...,Samaritan House,...,NaN,11 - 20%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We are a volunteer driven organization. Our cl...
4,4210509108,73895393,9/21/2015 20:06,9/21/2015 20:21,69.42.11.210,rodrigo@challengeday.org,Rodrigo,Torres,Visual Identity & Brand Strategy service grant...,Challenge Day,...,NaN,<1 %,NaN,NaN,NaN,We don’t know how to find high-quality pro bon...,We don’t know how we would use pro bono resour...,NaN,NaN,NaN

In [16]:
pbc_df = pd.read_csv(extra_path + "PBC End of Project Evaluation - 2015.csv", skiprows = 2, prefix="pbc_", header=None)
pbc_df.head()

,pbc_0,pbc_1,pbc_2,pbc_3,pbc_4,pbc_5,pbc_6,pbc_7,pbc_8,pbc_9,...,pbc_64,pbc_65,pbc_66,pbc_67,pbc_68,pbc_69,pbc_70,pbc_71,pbc_72,pbc_73
0,4229942890,73893194,9/30/2015 22:19,9/30/2015 22:36,73.170.60.119,cterdiman@gmail.com,Cynthia,Terdiman,Family Violence Law Center,San Francisco Bay Area,...,<br>4,<br>4,NaN,NaN,NaN,<br>4,<br>3,NaN,<br>3,NaN
1,4229564376,73893194,9/30/2015 14:13,9/30/2015 20:29,98.234.182.122,geri@thewebdom.com,Geraldine,Macomber,Family Violence Law Center,San Francisco Bay Area,...,<br>4,<br>4,Not at all likely<br>1,<br>2,Not at all likely<br>1,<br>2,NaN,NaN,Extremely likely<br>5,I joined Taproot to work with other profession...
2,4224127001,73893194,9/28/2015 18:37,9/28/2015 18:44,47.22.145.210,shanflan83@gmail.com,Shannon,Flannigan,Dance Theatre Etcetera,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4222452342,73893194,9/28/2015 1:21,9/28/2015 2:10,96.225.97.193,robert.stjacques@gmail.com,Robert,St Jacques,Dance Theatre Etcetera,New York,...,NaN,NaN,NaN,NaN,<br>4,<br>4,<br>2,NaN,Not at all likely<br>1,NaN
4,4220299202,73320803,9/25/2015 20:52,9/25/2015 20:59,104.129.192.60,wryanberger@gmail.com,Ryan,Berger,Big Up Kidz,Los Angeles,...,Extremely likely<br>5,Extremely likely<br>5,Extremely likely<br>5,Extremely likely<br>5,<br>4,Extremely likely<br>5,<br>2,NaN,Extremely likely<br>5,NaN

### Second Challenge
When looking through the columns some of the numerical columns are a bit messy as they seem to be dumps right from the HTML page. For instance if we look at the question "I wanted to do Pro Bono" in the pbc file, the numerical values are mixed in with html tags and human descriptions. For the purpose of my analysis I'll have to strip these out

In [17]:
pbc_df["pbc_21"]

0                      <br>4
1                      <br>2
2                      <br>2
3                      <br>4
4                        NaN
5                      <br>3
6      Achieved greatly<br>5
7                        NaN
8      Achieved greatly<br>5
9      Achieved greatly<br>5
10                     <br>4
11     Achieved greatly<br>5
12                       NaN
13     Achieved greatly<br>5
14                       NaN
15                     <br>4
16                     <br>4
17     Achieved greatly<br>5
18                     <br>4
19                     <br>3
20                     <br>4
21                     <br>3
22     Achieved greatly<br>5
23     Achieved greatly<br>5
24                     <br>4
25                     <br>3
26                     <br>4
27     Achieved greatly<br>5
28                     <br>4
29                     <br>2
               ...
280    Achieved greatly<br>5
281                    <br>4
282                      NaN
283    Achieved greatly<br>5
284    Achieved greatly<br>5
285    Achieved greatly<br>5
286                      NaN
287                      NaN
288                    <br>4
289    Achieved greatly<br>5
290                      NaN
291    Achieved greatly<br>5
292    Achieved greatly<br>5
293                    <br>4
294                      NaN
295    Achieved greatly<br>5
296    Achieved greatly<br>5
297                    <br>4
298                    <br>4
299                    <br>4
300    Achieved greatly<br>5
301                    <br>4
302    Achieved greatly<br>5
303                    <br>4
304                      NaN
305    Achieved greatly<br>5
306    Achieved greatly<br>5
307                    <br>4
308    Achieved greatly<br>5
309                    <br>3
Name: pbc_21, dtype: object